#!/usr/bin/env python3
"""Analyze profiling results and compare performance.

This script helps analyze .prof files generated by profiling scripts.

Usage:
    python profiling/analyze_performance.py profile_file.prof [top_n]
    python profiling/analyze_performance.py --compare file1.prof file2.prof
"""

import sys
import pstats
from pathlib import Path


def analyze_profile(profile_file: str, top_n: int = 30):
    """Analyze a single profile file."""
    if not Path(profile_file).exists():
        print(f"Error: Profile file not found: {profile_file}")
        return

    print(f"Analyzing: {profile_file}")
    print("=" * 70)

    stats = pstats.Stats(profile_file)

    print(f"\n=== Top {top_n} functions by cumulative time ===")
    stats.sort_stats("cumulative")
    stats.print_stats(top_n)

    print(f"\n=== Top {top_n} functions by total time ===")
    stats.sort_stats("tottime")
    stats.print_stats(top_n)

    print(f"\n=== Top {top_n} functions by call count ===")
    stats.sort_stats("calls")
    stats.print_stats(top_n)


def compare_profiles(file1: str, file2: str):
    """Compare two profile files."""
    if not Path(file1).exists() or not Path(file2).exists():
        print("Error: One or both profile files not found")
        return

    print("Comparing profiles:")
    print(f"  Baseline: {file1}")
    print(f"  Current:  {file2}")
    print("=" * 70)

    stats1 = pstats.Stats(file1)
    stats2 = pstats.Stats(file2)

    # Get total times
    total1 = stats1.total_tt
    total2 = stats2.total_tt

    print("\nTotal execution time:")
    print(f"  Baseline: {total1:.3f}s")
    print(f"  Current:  {total2:.3f}s")

    if total1 > 0:
        change = ((total2 - total1) / total1) * 100
        if change > 0:
            print(f"  Change:   +{change:.1f}% (slower) ⚠️")
        elif change < 0:
            print(f"  Change:   {change:.1f}% (faster) ✓")
        else:
            print("  Change:   No change")

    print("\n=== Top 20 functions by cumulative time (Current) ===")
    stats2.sort_stats("cumulative")
    stats2.print_stats(20)


def print_usage():
    """Print usage information."""
    print("Usage:")
    print("  Analyze single profile:")
    print("    python analyze_performance.py profile_file.prof [top_n]")
    print()
    print("  Compare two profiles:")
    print("    python analyze_performance.py --compare baseline.prof current.prof")
    print()
    print("Examples:")
    print("  python analyze_performance.py profile_database_generation.prof")
    print("  python analyze_performance.py profile_titleformat.prof 50")
    print("  python analyze_performance.py --compare old.prof new.prof")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print_usage()
        sys.exit(1)

    if sys.argv[1] == "--compare":
        if len(sys.argv) < 4:
            print("Error: --compare requires two profile files")
            print_usage()
            sys.exit(1)
        compare_profiles(sys.argv[2], sys.argv[3])
    else:
        profile_file = sys.argv[1]
        top_n = int(sys.argv[2]) if len(sys.argv) > 2 else 30
        analyze_profile(profile_file, top_n)
